From openjdk:8-jre-alpine

MAINTAINER saikirangude@gmail.com

#WORKDIR /home/ec2-user/jenkins-home/workspace/Git-Maven-SonarQube-Nexus-Ansible-1/target

#RUN cd /home/ec2-user/jenkins-home/workspace/Git-Maven-SonarQube-Nexus-Ansible-1/target

ADD context.xml /usr/local/tomcat/webapps/manager/META-INF

ADD tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

ADD spring-boot-example2-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/spring-boot-example2-0.0.1-SNAPSHOT.war

#RUN ./usr/local/tomcat/bin/startup.sh

EXPOSE 8080

CMD ["catalina.sh", "run"]

#ENTRYPOINT ["/bin/bash", "/usr/local/tomcat/bin/startup.sh"]
